const STORAGE_SETTINGS='tlh_settings',STORAGE_REVIEWS='tlh_reviews',STORAGE_BOOKINGS='tlh_bookings',STORAGE_MESSAGES='tlh_messages';
const defaults={heroTitle:'Luxury Eyelash Extensions in Birmingham',heroSubtitle:'Bespoke lash artistry designed to enhance your natural beauty with soft, long-lasting, beautifully styled lash sets.',movingText:['New client appointments available this week','Luxury lash extensions in Birmingham','48-hour free cancellation window','Gift cards coming soon','Secure deposits through the website'],slots:['09:00','10:30','12:00','13:30','15:00','17:30'],instagram:'#',tiktok:'#',facebook:'#'};
const defaultReviews=[{name:'Amira',rating:'★★★★★',text:'My lashes lasted so well and looked amazing. The whole experience felt luxury.',status:'approved'},{name:'Chloe',rating:'★★★★★',text:'Beautiful studio, clean, professional and such lovely service.',status:'approved'}];
function getSettings(){return {...defaults,...JSON.parse(localStorage.getItem(STORAGE_SETTINGS)||'{}')}}function getReviews(){return JSON.parse(localStorage.getItem(STORAGE_REVIEWS)||'null')||defaultReviews}function setReviews(x){localStorage.setItem(STORAGE_REVIEWS,JSON.stringify(x))}function getBookings(){return JSON.parse(localStorage.getItem(STORAGE_BOOKINGS)||'[]')}function setBookings(x){localStorage.setItem(STORAGE_BOOKINGS,JSON.stringify(x))}function getMessages(){return JSON.parse(localStorage.getItem(STORAGE_MESSAGES)||'[]')}function setMessages(x){localStorage.setItem(STORAGE_MESSAGES,JSON.stringify(x))}function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
const toast=document.getElementById('toast');function showToast(m){toast.textContent=m;toast.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>toast.classList.remove('show'),2600)}
const menuBtn=document.getElementById('menuBtn'),navLinks=document.getElementById('navLinks');menuBtn.addEventListener('click',()=>navLinks.classList.toggle('open'));document.querySelectorAll('.links a').forEach(a=>a.addEventListener('click',()=>navLinks.classList.remove('open')));
function renderPublic(){const s=getSettings();heroTitle.textContent=s.heroTitle;heroSubtitle.textContent=s.heroSubtitle;movingTrack.innerHTML=[...s.movingText,...s.movingText].map(x=>`<span>${esc(x)}</span>`).join('');slotList.innerHTML=s.slots.map((slot,i)=>`<button type="button" class="slot ${i===0?'active':''}">${esc(slot)}</button>`).join('');slotList.querySelectorAll('.slot').forEach(slot=>slot.addEventListener('click',()=>{slotList.querySelectorAll('.slot').forEach(x=>x.classList.remove('active'));slot.classList.add('active')}));instagramLink.href=s.instagram;tiktokLink.href=s.tiktok;facebookLink.href=s.facebook;reviewList.innerHTML=getReviews().filter(r=>r.status==='approved').map(r=>`<article class="review-card"><p class="stars">${esc(r.rating)}</p><p>“${esc(r.text)}”</p><strong>${esc(r.name)}</strong></article>`).join('')}
beforeAfterSlider.addEventListener('input',e=>afterLayer.style.right=`${100-e.target.value}%`);
document.querySelectorAll('.photo').forEach(p=>p.addEventListener('click',()=>{lightboxImg.src=p.dataset.img;lightbox.classList.add('show')}));function hideLightbox(){lightbox.classList.remove('show');lightboxImg.src=''}closeLightbox.addEventListener('click',hideLightbox);lightbox.addEventListener('click',e=>{if(e.target===lightbox)hideLightbox()});document.addEventListener('keydown',e=>{if(e.key==='Escape')hideLightbox()});
function markMissing(form){let ok=true;form.querySelectorAll('input,select,textarea').forEach(f=>{if(!f.checkValidity()){f.classList.add('required-warning');ok=false}else f.classList.remove('required-warning')});return ok}
bookingForm.addEventListener('submit',e=>{e.preventDefault();if(!markMissing(bookingForm)){showToast('Please complete the booking form.');return}const booking={id:Date.now(),name:name.value,email:email.value,treatment:treatment.value,date:date.value,slot:document.querySelector('.slot.active')?.textContent||'',status:'pending',created:new Date().toLocaleString()};const list=getBookings();list.push(booking);setBookings(list);showToast('Booking request sent to admin.');bookingForm.reset();renderPublic()});
contactForm.addEventListener('submit',e=>{e.preventDefault();if(!markMissing(contactForm)){showToast('Please complete the enquiry form.');return}const msg={id:Date.now(),name:contactName.value,email:contactEmail.value,text:message.value,status:'new',created:new Date().toLocaleString()};const list=getMessages();list.push(msg);setMessages(list);showToast('Message sent to admin.');contactForm.reset()});
reviewForm.addEventListener('submit',e=>{e.preventDefault();if(!markMissing(reviewForm)){showToast('Please complete your review.');return}const list=getReviews();list.push({name:reviewName.value,rating:reviewRating.value,text:reviewText.value,status:'pending',created:new Date().toLocaleString()});setReviews(list);showToast('Review submitted for approval.');reviewForm.reset()});
[instagramLink,tiktokLink,facebookLink].forEach(a=>a.addEventListener('click',e=>{if(a.getAttribute('href')==='#'){e.preventDefault();showToast('Social link coming soon.')}}));
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');revealObserver.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>revealObserver.observe(el));window.addEventListener('storage',renderPublic);renderPublic();